### ISSUE TITLE
Inventory Database

### ISSUE THREAD

**Issue by jacksonjunelee** [jjlee5266/DatabaseApp#2]
@harimohanraj89 @htella @DrRobotmck 

For my Inventory manager I defined inventory and locations as a one to many relationship. However, as I was programming I found that I want my inventory to be different for each branch and headquarters. Because the amount of inventory and amount they sell per day is different for each branch and headquarters. However, headquarters and branches are related to each other through a self-join. Is it possible to have inventory related to branches through the headquarters or do I have to change the relationship to a many to many with inventory and locations.

**Comment by harimohanraj89** [comment]
I don't think you need to change the relationship. You may need to add some additional logic to your models to achieve the functionality that you want. The relationship is still valid.

**Comment by jacksonjunelee** [comment]
What do you mean by additional logic?

**Comment by jacksonjunelee** [comment]
I have been thinking about but I can't think of the additional logic that makes the 1 to many relationship true. I am thinking of making it a many to many but I do not want to set up a join table because it is one more table to keep track of

**Comment by harimohanraj89** [comment]
Oh! I think I misunderstood your first statement. Is your current relationship that one inventory has many locations? If so, you are correct, that relationship will not work because each location needs its own inventory. In order to do that, you need to set up a one to many relationship that goes the other way. One location has many inventories. To be more efficient, you can set up a one-to-one relationship (one location has one inventory), with a `location_id` on the `inventories` table.

**Comment by jacksonjunelee** [comment]
I think you are misunderstanding. I currently have one location has many inventories. But inventories has the parameters: "product_name", "amount_inhouse", "amount_sold", "price" that differs by branch. How can I have a one to many relationship or one to one relationship when those parameters change based on branches and headquarters
